# for kompose convert: not support "network": 
# 	https://github.com/kubernetes/kompose/blob/master/docs/conversion.md
# this Kafka Docker setting is to support a client myservice1 in Docker container, 
# also to support myservice1 running locally (on Docker-host machine: localhost)
version: "3.0"
    
services:
  mysql1:
    image: mysql:8.0.20
    container_name: mysql1
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "V4321abcd!"
      MYSQL_USER: user1
      MYSQL_PASSWORD: "V4321abcd!"
      MYSQL_DATABASE: "MyDB"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
  
# There are three listeners: 
# INTERNAL: for internal traffic on the Docker network
# EXTERNAL: for traffic from the Docker-host machine (localhost)
# DOMAIN1 for traffic from outside, reaching the Docker host on the DNS name 'dns1'
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29094:29094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://kafka1:9092,DOMAIN1://kafka1:29094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092,DOMAIN1://dns1:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOMAIN1:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      ALLOW_PLAINTEXT_LISTENER: "yes"
      
  myservice1:
    container_name: myservice1
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: zmg9046/myservice1:tag-1.0.0
    ports:
      - 8082:8082
    environment:
      KAFKA_URI: kafka1:29092
      mysql-servername: mysql1
      mysql-db: "MyDB"
      spring_datasource_username: "user1"
      spring_datasource_password: "V4321abcd!"
      spring_datasource_url: jdbc:mysql://mysql1:3306/MyDB?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - kafka1
      - mysql1
