apiVersion: v1
kind: Service
metadata:
  name: {{ include "service3chart.fullname" . }}
  labels:
    {{- include "service3chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "service3chart.selectorLabels" . | nindent 4 }}
  #loadBalancerIP only works if it is supported by cloud provider otherwise it is ignored
  {{- if .Values.service.loadBalancerStaticIpEnabled }}
  loadBalancerIP: {{ .Values.service.loadBalancerStaticIp }}
  {{- end }}
  