# this setting is OK when Kafka is in Docker container with a client running locally
# but not work when both Kafka and client in Docker container
version: "3.0"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
  # Since both zookeeper and kafka services are going to be a part of the same 
  # bridge network, we don’t need to expose any ports. Kafka broker can talk 
  # to zookeeper and that’s all the communication zookeeper needs.
  
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      