# choose exact tag (not 'latest'), to be sure that new version wont break creating image
# FROM mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04
FROM mcr.microsoft.com/mssql/server:2017-latest

# Create a config directory
RUN mkdir -p /usr/config
WORKDIR /usr/config

# Bundle config source
COPY . /usr/config

# Grant permissions for to our scripts to be executable
RUN chmod +x /usr/config/entrypoint-mssql.sh
RUN chmod +x /usr/config/configure-mssql.sh

ENTRYPOINT ["./entrypoint-mssql.sh"]

# Tail the setup logs to trap the process
CMD ["tail -f /dev/null"]

HEALTHCHECK --interval=15s CMD /opt/mssql-tools/bin/sqlcmd -U sa -P $SA_PASSWORD -Q "select 1" && grep -q "MSSQL CONFIG COMPLETE" ./config.log
