CREATE DATABASE $(MSSQL_DB);
GO
USE $(MSSQL_DB);
GO
CREATE LOGIN $(MSSQL_USER) WITH PASSWORD = '$(MSSQL_PASSWORD)';
GO
CREATE USER $(MSSQL_USER) FOR LOGIN $(MSSQL_USER);
GO
ALTER SERVER ROLE sysadmin ADD MEMBER [$(MSSQL_USER)];
GO

CREATE TABLE [dbo].[users]
( 	  [id] INT NOT NULL
	, [disabled] BIT NOT NULL
	, [email] VARCHAR(255) NOT NULL
	, [name] VARCHAR(255) NOT NULL
	, CONSTRAINT [PK__users] PRIMARY KEY ([id] ASC)
);
GO
