# using maven from Docker to build .jar
FROM maven:3.5.2-jdk-8-alpine AS MAVEN_TOOL_CHAIN
COPY pom.xml /tmp/
COPY src /tmp/src/
WORKDIR /tmp/
RUN mvn clean package -Dmaven.test.skip=true

# For Java 8, try this
FROM openjdk:8-jdk-alpine

# For Java 11, try this
# FROM adoptopenjdk/openjdk11:alpine-jre

MAINTAINER unistar.com

VOLUME /tmp
EXPOSE 8080

COPY --from=MAVEN_TOOL_CHAIN /tmp/target/*.jar myservice3.jar
# COPY target/*.jar myservice3.jar

ENTRYPOINT java -jar myservice3.jar
