apiVersion: v1
description: A Helm chart for myservice1 , mysql and kafka
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: myservice1app
version: 0.1.0-SNAPSHOT 
