apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  name: mysql1
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: {{ quote .Values.auth.database }}
        - name: MYSQL_ROOT_PASSWORD
          value: {{ quote .Values.auth.rootPassword }}
        - name: MYSQL_USER
          value: {{ quote .Values.auth.username }}
        - name: MYSQL_PASSWORD
          value: {{ quote .Values.auth.password }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: ""
        name: mysql1
        ports:
        - containerPort: {{ .Values.service.port }}
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
