apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  name: mysql1
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: mysql1
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
status:
  loadBalancer: {}
